name: Deploy

on:
  repository_dispatch:
    types: [deploy-test-command]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: test
        run: |
          echo "Hello deploy!"